name: chat_app
description: A new Flutter project.
version: 1.0.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  # For using cupertino icons
  cupertino_icons: ^1.0.2
  
  # For integrating firebase
  firebase_core: ^2.2.0

  # For handling firebase authentication
  firebase_auth: ^4.1.3

  # For handling google sign in
  google_sign_in: ^5.4.2

  # For accessing cloud firestore database
  cloud_firestore: ^4.1.0

  # For showing network images
  cached_network_image: ^3.2.3

  # For picking images
  image_picker: ^0.8.6

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^11.0.6

  # For showing Emojis
  emoji_picker_flutter: ^1.5.1

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^14.2.0

  # For calling RestAPIs
  http: ^0.13.5

  # For creating notification channel
  flutter_notification_channel: ^2.0.0

  # For storing images into gallery
  gallery_saver: ^2.3.2

  provider: ^6.1.1
  agora_uikit: ^1.3.7
  flutter_callkit_incoming: ^2.0.0+2
  # agora_rtm: ^1.5.8
  change_app_package_name:
  # agora_rtc_engine: ^6.2.6
  quick_actions: ^1.0.6
  # zego_uikit_prebuilt_call: ^3.17.10

  # cupertino_icons: ^1.0.2
  # firebase_core: ^2.22.0
  # google_sign_in: ^6.1.6
  # firebase_auth: ^4.13.0
  # cloud_firestore: ^4.13.0
  # cached_network_image: ^3.3.0
  # image_picker: ^1.0.4
  # firebase_storage: ^11.5.0
  # emoji_picker_flutter: ^1.6.3
  # firebase_messaging: ^14.7.4
  # http:
  # flutter_notification_channel: ^2.0.0
  # gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CrimsonText
      fonts:
        - asset: fonts/Crimson_Text/CrimsonText-Bold.ttf
        - asset: fonts/Crimson_Text/CrimsonText-Italic.ttf
        - asset: fonts/Crimson_Text/CrimsonText-BoldItalic.ttf
        - asset: fonts/Crimson_Text/CrimsonText-Regular.ttf
        - asset: fonts/Crimson_Text/CrimsonText-SemiBold.ttf
        - asset: fonts/Crimson_Text/CrimsonText-SemiBoldItalic.ttf
    #       style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
